package com.shx.law.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shx.law.dao.LawItem;

import com.shx.law.dao.LawItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lawItemDaoConfig;

    private final LawItemDao lawItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lawItemDaoConfig = daoConfigMap.get(LawItemDao.class).clone();
        lawItemDaoConfig.initIdentityScope(type);

        lawItemDao = new LawItemDao(lawItemDaoConfig, this);

        registerDao(LawItem.class, lawItemDao);
    }
    
    public void clear() {
        lawItemDaoConfig.clearIdentityScope();
    }

    public LawItemDao getLawItemDao() {
        return lawItemDao;
    }

}
